services:
  db:
    container_name: db
    image: mysql
    restart: always
    env_file:
      - ./.env
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ROOT_USER: $MYSQLDB_ROOT_USER
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}

  app:
    depends_on:
      - db
    image: book-store
    restart: on-failure
    container_name: app
    build: .
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:mysql://db:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}",
          "spring.datasource.username" : "${MYSQLDB_ROOT_USER}",
          "spring.datasource.password" : "${MYSQLDB_ROOT_PASSWORD}",
          "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver"  
        }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
